[tool.poetry]
name = "web-hw-3"
version = "0.1.0"
description = "File sort and factorize func"
authors = ["Vlad <vlad111121562@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
